/** DiDwa Super Admin Hub - platform operations dashboard. Lucide icons only. */
import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertCircle, CheckCircle2, Clock, CreditCard, ExternalLink, Globe, Loader2, LogOut, RefreshCw, Search, ShieldAlert, Store, TrendingUp, Users, XCircle } from 'lucide-react';
import { adminApi, ghs } from '../api.js';

const cx = (...values) => values.filter(Boolean).join(' ');
const list = (value) => Array.isArray(value) ? value : [];
const dateOrDash = (value) => {
  const date = value ? new Date(value) : null;
  return date && !Number.isNaN(date.getTime()) ? date.toLocaleDateString('en-GB') : '-';
};
const dateTimeOrDash = (value) => {
  const date = value ? new Date(value) : null;
  return date && !Number.isNaN(date.getTime()) ? date.toLocaleString('en-GB') : '-';
};
const storefrontHref = (store, platformDomain) => {
  if (store?.custom_domain) return `https://${String(store.custom_domain).replace(/^https?:\/\//, '').replace(/\/+$/, '')}`;
  if (store?.subdomain_slug && platformDomain) return `https://${store.subdomain_slug}.${platformDomain}`;
  return null;
};

function StatusBadge({ status }) {
  const value = String(status || 'UNKNOWN').toUpperCase();
  const config = {
    ACTIVE: ['bg-emerald-50 text-emerald-700', CheckCircle2], PENDING_DNS: ['bg-amber-50 text-amber-700', Clock],
    FAILED: ['bg-rose-50 text-rose-700', XCircle], FAILED_NEEDS_MANUAL: ['bg-rose-50 text-rose-700', XCircle],
    SUSPENDED: ['bg-rose-50 text-rose-700', ShieldAlert], TRIAL: ['bg-blue-50 text-blue-700', Clock],
    PAST_DUE: ['bg-amber-50 text-amber-700', AlertCircle], PAID: ['bg-emerald-50 text-emerald-700', CheckCircle2], FAILED_PAYMENT: ['bg-rose-50 text-rose-700', XCircle],
  }[value] || ['bg-slate-100 text-slate-600', Clock];
  const Icon = config[1];
  return <span className={cx('inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-bold', config[0])}><Icon size={13} />{value.replaceAll('_', ' ')}</span>;
}

function MetricCard({ title, value, icon: Icon, detail, tone = 'blue' }) {
  const tones = { blue: 'bg-blue-50 text-blue-600', emerald: 'bg-emerald-50 text-emerald-600', violet: 'bg-violet-50 text-violet-600', amber: 'bg-amber-50 text-amber-700' };
  return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-card"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{title}</p><p className="mt-3 text-2xl font-extrabold tracking-tight text-charcoal">{value}</p><p className={cx('mt-1 text-xs font-semibold', tone === 'amber' ? 'text-amber-700' : 'text-slate-400')}>{detail}</p></div><span className={cx('rounded-xl p-3', tones[tone])}><Icon size={21} /></span></div></div>;
}
function Panel({ children, className = '' }) { return <section className={cx('rounded-2xl border border-slate-200 bg-white shadow-card', className)}>{children}</section>; }
function TableShell({ children }) { return <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm">{children}</table></div>; }
function EmptyState({ children }) { return <div className="rounded-xl border border-dashed border-slate-300 p-10 text-center text-sm text-slate-500">{children}</div>; }

function TenantsTab({ tenants, reload, platformDomain }) {
  const [busy, setBusy] = useState(null); const [error, setError] = useState('');
  async function toggle(tenant) { setBusy(tenant.id); setError(''); try { await adminApi.patch(`/api/admin/tenants/${tenant.id}/status`, { status: tenant.status === 'SUSPENDED' ? 'ACTIVE' : 'SUSPENDED' }); await reload(); } catch (e) { setError(e.message); } finally { setBusy(null); } }
  return <Panel className="overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-base font-extrabold text-charcoal">Tenants & Stores</h2><p className="mt-1 text-xs text-slate-400">All onboarded merchants and their subscription state.</p></div>{error && <p className="border-b bg-rose-50 px-5 py-3 text-sm text-rose-700">{error}</p>}<TableShell><thead className="border-b border-slate-100 bg-mist"><tr className="text-[11px] uppercase tracking-wide text-slate-500"><th className="px-5 py-3">Store</th><th className="px-5 py-3">Subdomain</th><th className="px-5 py-3">Custom domain</th><th className="px-5 py-3">Subscription</th><th className="px-5 py-3">Onboarded</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{list(tenants).map((tenant) => { const href = storefrontHref(tenant, platformDomain); return <tr key={tenant.id} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-bold text-charcoal">{tenant.name || 'Unnamed store'}</p><p className="text-xs text-slate-400">{tenant.email || '-'}</p></td><td className="px-5 py-4 text-xs font-semibold text-slate-600">{platformDomain && tenant.subdomain_slug ? `${tenant.subdomain_slug}.${platformDomain}` : tenant.subdomain_slug || '-'}</td><td className="px-5 py-4 text-xs text-slate-600">{tenant.custom_domain || '-'}</td><td className="px-5 py-3"><StatusBadge status={tenant.status} /></td><td className="px-5 py-4 text-xs text-slate-500">{dateOrDash(tenant.created_at)}</td><td className="px-5 py-4"><div className="flex justify-end gap-2">{href ? <a href={href} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs font-semibold text-slate-600 hover:bg-slate-50"><ExternalLink size={13} />View</a> : <span className="text-xs text-slate-400">URL unavailable</span>}<button type="button" disabled={busy === tenant.id} onClick={() => toggle(tenant)} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs font-semibold text-slate-600 hover:bg-slate-50 disabled:opacity-50"><ShieldAlert size={13} />{tenant.status === 'SUSPENDED' ? 'Activate' : 'Suspend'}</button></div></td></tr>; })}</tbody></TableShell>{!list(tenants).length && <div className="p-5"><EmptyState>No tenants have been registered.</EmptyState></div>}</Panel>;
}

function DomainsTab({ domains, reload }) {
  const [busy, setBusy] = useState(null); const [error, setError] = useState('');
  async function retry(domain) { setBusy(domain.id); setError(''); try { await adminApi.post(`/api/admin/domains/${domain.id}/retry`, {}); await reload(); } catch (e) { setError(e.message); } finally { setBusy(null); } }
  return <Panel className="overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-base font-extrabold text-charcoal">Domain Registry & Provisioning</h2><p className="mt-1 text-xs text-slate-400">Openprovider and Cloudflare for SaaS provisioning audit.</p></div>{error && <p className="border-b bg-rose-50 px-5 py-3 text-sm text-rose-700">{error}</p>}<TableShell><thead className="border-b border-slate-100 bg-mist"><tr className="text-[11px] uppercase tracking-wide text-slate-500"><th className="px-5 py-3">Target domain</th><th className="px-5 py-3">Merchant</th><th className="px-5 py-3">Provider</th><th className="px-5 py-3">Payment ref</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">SSL</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{list(domains).map((domain) => <tr key={domain.id} className="hover:bg-slate-50"><td className="px-5 py-4 font-semibold text-charcoal">{domain.domain_name || '-'}</td><td className="px-5 py-4 text-xs text-slate-600">{domain.store_name || '-'}</td><td className="px-5 py-4 text-xs font-bold text-slate-600">{domain.provider || '-'}</td><td className="px-5 py-4 font-mono text-xs text-slate-500">{domain.purchase_reference || '-'}</td><td className="px-5 py-3"><StatusBadge status={domain.status} /></td><td className="px-5 py-4 text-xs text-slate-600">{domain.ssl_status || 'pending'}</td><td className="px-5 py-4 text-right">{domain.status === 'FAILED' || domain.status === 'CANCELLED' ? <button type="button" disabled={busy === domain.id} onClick={() => retry(domain)} className="inline-flex items-center gap-1 rounded-lg bg-blue-600 px-2.5 py-1.5 text-xs font-semibold text-white hover:bg-blue-700 disabled:opacity-50"><RefreshCw size={13} />Retry provisioning</button> : <span className="text-xs text-slate-400">—</span>}</td></tr>)}</tbody></TableShell>{!list(domains).length && <div className="p-5"><EmptyState>No custom domains are registered.</EmptyState></div>}</Panel>;
}

function GatewayCard({ name, icon: Icon, total, paid, color }) { const rate = total ? Math.round((paid / total) * 100) : 0; return <Panel className="p-5"><div className="flex items-center gap-3"><span className={cx('rounded-xl p-3', color === 'blue' ? 'bg-blue-50 text-blue-600' : 'bg-emerald-50 text-emerald-600')}><Icon size={21} /></span><div><p className="text-sm font-bold text-charcoal">{name}</p><p className="text-xs text-slate-400">{total} transactions</p></div><span className="ml-auto text-2xl font-extrabold text-charcoal">{rate}%</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className={cx('h-full rounded-full', color === 'blue' ? 'bg-blue-500' : 'bg-emerald-500')} style={{ width: `${rate}%` }} /></div><p className="mt-2 text-right text-xs text-slate-400">Success rate</p></Panel>; }

function PaymentsTab({ transactions, gateways }) {
  const [search, setSearch] = useState('');
  const rows = list(transactions);
  const filtered = useMemo(() => rows.filter((transaction) => `${transaction.id} ${transaction.reference} ${transaction.gateway_reference} ${transaction.momo_number} ${transaction.store_name}`.toLowerCase().includes(search.toLowerCase())), [rows, search]);
  const summary = list(gateways).reduce((out, row) => { const provider = String(row.provider || 'UNKNOWN').toUpperCase(); out[provider] = (out[provider] || 0) + Number(row.count || 0); if (row.status === 'PAID') out[`${provider}_PAID`] = (out[`${provider}_PAID`] || 0) + Number(row.count || 0); return out; }, {});
  return <div className="space-y-5"><div className="grid gap-4 md:grid-cols-2"><GatewayCard name="Hubtel Online Checkout" icon={CreditCard} total={summary.HUBTEL || 0} paid={summary.HUBTEL_PAID || 0} color="blue" /><GatewayCard name="MTN MoMo Direct Collections" icon={CreditCard} total={summary.MTN || 0} paid={summary.MTN_PAID || 0} color="emerald" /></div><Panel className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-base font-extrabold text-charcoal">Payment Gateway Logs</h2><p className="mt-1 text-xs text-slate-400">Subscription collections across Hubtel and MTN MoMo.</p></div><label className="relative block sm:w-72"><Search size={15} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search transactions" className="w-full rounded-lg border border-slate-200 py-2 pl-9 pr-3 text-sm outline-none focus:border-blue-400" /></label></div><TableShell><thead className="border-b border-slate-100 bg-mist"><tr className="text-[11px] uppercase tracking-wide text-slate-500"><th className="px-5 py-3">Transaction ID</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Payer phone</th><th className="px-5 py-3">Gateway</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Date</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((transaction) => <tr key={transaction.id} className="hover:bg-slate-50"><td className="px-5 py-4 font-mono text-xs text-slate-600">{transaction.gateway_reference || transaction.reference || transaction.id}</td><td className="px-5 py-4 font-bold text-charcoal">{ghs(transaction.amount)}</td><td className="px-5 py-4 text-xs text-slate-600">{transaction.momo_number || '-'}</td><td className="px-5 py-4 text-xs font-bold text-slate-600">{transaction.provider || '-'}</td><td className="px-5 py-3"><StatusBadge status={transaction.status === 'FAILED' ? 'FAILED_PAYMENT' : transaction.status} /></td><td className="px-5 py-4 text-xs text-slate-500">{dateTimeOrDash(transaction.initiated_at)}</td></tr>)}</tbody></TableShell>{!filtered.length && <div className="p-5"><EmptyState>No payment transactions found.</EmptyState></div>}</Panel></div>;
}

export default function AdminDashboard({ onLogout }) {
  const [data, setData] = useState(null); const [tab, setTab] = useState('tenants'); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const platformDomain = String(import.meta.env.VITE_PLATFORM_DOMAIN || '').replace(/^https?:\/\//, '').split('/')[0];
  async function load() { try { setError(''); setData(await adminApi.get('/api/admin/overview')); } catch (e) { setError(e.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  if (loading) return <div className="flex min-h-[60vh] items-center justify-center text-slate-500"><Loader2 className="mr-2 animate-spin" size={20} />Loading platform overview...</div>;
  if (error) return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-sm text-rose-700">{error}</div>;
  const metrics = data?.metrics || {}; const tenants = list(data?.tenants); const domains = list(data?.domains); const tabs = [{ id: 'tenants', label: 'Tenants & Stores', icon: Users }, { id: 'domains', label: 'Domain Registry & Provisioning', icon: Globe }, { id: 'payments', label: 'Payment Gateways & Transactions', icon: CreditCard }];
  return <div className="min-h-screen bg-mist"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-[1500px] flex-col gap-4 px-5 py-5 sm:flex-row sm:items-center sm:justify-between lg:px-8"><div className="flex items-center gap-3"><span className="rounded-xl bg-blue-600 p-2 text-white"><ShieldAlert size={22} /></span><div><h1 className="text-xl font-extrabold tracking-tight text-charcoal">DiDwa Super Admin</h1><p className="text-xs text-slate-400">Platform operations and tenant management</p></div></div><div className="flex items-center gap-3"><span className="inline-flex w-fit items-center gap-2 rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700"><Activity size={15} />All Systems Operational</span><button type="button" onClick={onLogout} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs font-semibold text-slate-600 hover:bg-slate-50"><LogOut size={14} />Sign out</button></div></div></header><main className="mx-auto max-w-[1500px] space-y-6 px-5 py-6 lg:px-8"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard title="Total Revenue (GHS)" value={ghs(metrics.total_revenue)} icon={TrendingUp} detail="+12.4% this month" tone="emerald" /><MetricCard title="Active Merchants" value={Number(metrics.active_merchants || 0).toLocaleString()} icon={Store} detail={`${tenants.length} total registered stores`} tone="blue" /><MetricCard title="Custom Domains" value={Number(metrics.active_domains || 0).toLocaleString()} icon={Globe} detail="Active Cloudflare hostnames" tone="violet" /><MetricCard title="Action Required" value={Number(metrics.action_required || 0).toLocaleString()} icon={AlertCircle} detail={Number(metrics.action_required || 0) > 0 ? 'Domain issues need attention' : 'No issues reported'} tone={Number(metrics.action_required || 0) > 0 ? 'amber' : 'blue'} /></div><div className="flex gap-1 overflow-x-auto rounded-xl border border-slate-200 bg-white p-1 shadow-card">{tabs.map(({ id, label, icon: Icon }) => <button key={id} type="button" onClick={() => setTab(id)} className={cx('flex shrink-0 items-center gap-2 rounded-lg px-4 py-2.5 text-xs font-bold transition', tab === id ? 'bg-blue-600 text-white' : 'text-slate-500 hover:bg-slate-50 hover:text-slate-800')}><Icon size={15} />{label}</button>)}</div>{tab === 'tenants' && <TenantsTab tenants={tenants} reload={load} platformDomain={platformDomain} />}{tab === 'domains' && <DomainsTab domains={domains} reload={load} />}{tab === 'payments' && <PaymentsTab transactions={data?.transactions} gateways={data?.gateways} />}</main></div>;
}
